"""Regenerate widget.css from the real widget's stylesheet.

    python tools/sync-widget-css.py

Reads ../orli-calendar/widget/src/style.css and rewrites widget.css as the
same rules scoped under .orli-live (see the header it writes for the exact
mapping and what is dropped). Not a build step: run it by hand whenever
the real widget's style.css changes, then review the diff and reload.
"""
import io
import os
import re
import textwrap

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, '..', '..', 'orli-calendar', 'widget', 'src', 'style.css')
OUT = os.path.join(HERE, '..', 'widget.css')

HEADER = '''/* ===========================================================
   Live Orli booking widget — the real product's stylesheet,
   scoped under .orli-live so it never touches the marketing site.

   GENERATED by tools/sync-widget-css.py from
   ../orli-calendar/widget/src/style.css — edit that, or the
   "Marketing-site additions" block in the script, not this file.
   Everything up to the additions block is style.css transformed
   mechanically, rule for rule:
     :root, body      -> .orli-live      (tokens + typography; body's
                                          margin/overflow dropped)
     *, button, input -> .orli-live *, .orli-live button, ...
     [dir="x"] ...    -> .orli-live[dir="x"] ...
     everything else  -> .orli-live <selector>
   Dropped on purpose: the clinic font-choice @imports (the demo has
   no clinic theme, only Heebo), the phone full-screen @media block
   (the widget is framed here, never the whole viewport), and the
   manage-an-existing-booking rules (reached from an emailed link,
   never from this flow).
   =========================================================== */
@import url("https://fonts.googleapis.com/css2?family=Heebo:wght@300;400;500;600;700&display=swap");

'''

ADDITIONS = '''
/* ===========================================================
   Marketing-site additions — not in style.css.
   =========================================================== */
.orli-live { display: block; text-align: start; }

/* The pinned #demo card owns the frame's size (styles.css .demo-browser), so
   the widget fills it instead of restating style.css's 400x580 defaults. */
.orli-live[data-scrolly] .obw-widget { max-width: none; height: 100%; }

/* Demo-only "any 6 digits" note, inline after the resend link so it adds no
   height to the confirm step (see widget.js S.otpDemoHint). */
.orli-live .obw-demo-hint { display: inline; margin-inline-start: 10px; font-size: .8rem; color: var(--obw-muted); }

/* Demo-only exit on the success scene (see widget.js S.restartDemo). */
.orli-live .obw-success-actions { margin-block-start: 16px; }
.orli-live .obw-restart-btn {
  font: inherit; font-size: .82rem; font-weight: 600; line-height: 1;
  padding: 9px 16px; border-radius: var(--obw-radius-pill);
  border: 1px solid var(--obw-border); background: transparent;
  color: var(--obw-muted); cursor: pointer;
}
.orli-live .obw-restart-btn:hover { border-color: var(--obw-border-strong); color: var(--obw-text); }
'''


def split_selectors(head):
    parts, depth, cur = [], 0, ''
    for ch in head:
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        if ch == ',' and depth == 0:
            parts.append(cur.strip())
            cur = ''
        else:
            cur += ch
    parts.append(cur.strip())
    return parts


def prefix(sel):
    if sel in (':root', 'body'):
        return '.orli-live'
    if sel == '*':
        return '.orli-live *'
    if sel.startswith('[dir='):
        return '.orli-live' + sel
    return '.orli-live ' + sel


def tokens(css):
    i, n, out = 0, len(css), []
    while i < n:
        m = re.match(r'\s+', css[i:])
        if m:
            i += m.end()
            continue
        if css.startswith('/*', i):
            j = css.index('*/', i) + 2
            out.append(('comment', css[i:j]))
            i = j
            continue
        if css.startswith('@import', i):
            # The font URLs carry semicolons of their own (wght@300;400;...),
            # so the statement ends at the first ';' after the closing ')'.
            j = css.index(';', css.index(')', i)) + 1
            out.append(('import', css[i:j]))
            i = j
            continue
        j = css.index('{', i)
        head = css[i:j].strip()
        depth, k = 0, j
        while True:
            if css[k] == '{':
                depth += 1
            elif css[k] == '}':
                depth -= 1
                if depth == 0:
                    break
            k += 1
        out.append(('rule', head, css[j + 1:k]))
        i = k + 1
    return out


def body_decls(body):
    keep = []
    for d in body.split(';'):
        d = d.strip()
        if not d:
            continue
        if d.split(':')[0].strip() in ('margin', 'overflow'):
            continue
        keep.append(d + ';')
    return '\n'.join(keep)


def indent_block(text, indent):
    text = textwrap.dedent(text).strip('\n')
    return '\n'.join((indent + l) if l.strip() else '' for l in text.split('\n'))


def render(toks, indent=''):
    out, pending = [], []
    for t in toks:
        if t[0] == 'comment':
            pending.append(t[1])
            continue
        if t[0] == 'import':
            pending = []
            continue
        head, body = t[1], t[2]
        if head.startswith('@media'):
            if 'prefers-reduced-motion' not in head:
                pending = []
                continue
            out.extend(indent_block(p, indent) for p in pending)
            pending = []
            out.append(indent + head + ' {')
            out.append(render(tokens(body), indent + '  '))
            out.append(indent + '}\n')
            continue
        out.extend(indent_block(p, indent) for p in pending)
        pending = []
        sels = ', '.join(prefix(s) for s in split_selectors(head))
        decl = body_decls(body) if head == 'body' else body
        out.append(indent + sels + ' {\n' + indent_block(decl, indent + '  ') + '\n' + indent + '}\n')
    return '\n'.join(out)


def main():
    src = io.open(SRC, encoding='utf-8-sig').read()
    src = src[:src.index('/* Manage-an-existing-booking view')]
    css = HEADER + render(tokens(src)).rstrip() + '\n' + ADDITIONS
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(css)
    print('wrote', os.path.relpath(OUT), len(css.splitlines()), 'lines')


if __name__ == '__main__':
    main()
